------------------------------- Sourcing ----------------------------------------

require "plugins.colorscheme"
require "plugins.file-tree"
require "plugins.finder"
require "plugins.parser"
require "plugins.auto-completion"
require "plugins.term"
require "plugins.undo-tree"
require "plugins.diff-view"
require "plugins.icons"
require "plugins.statusline"
require "plugins.whichkey"
require "plugins.launch-screen"
require "plugins.auto-pairs"
require "plugins.etc"
require "plugins.tabline"
require "plugins.git"
